'use client';
import { useEffect, useRef, useState } from 'react';
type Mode='menu'|'play'|'upgrade'|'pause'|'over'|'howto'|'settings';
type Entity={x:number;y:number;r:number;hp:number;max:number;speed:number;kind:number;cool:number};
type Shot={x:number;y:number;vx:number;vy:number;life:number;friendly:boolean;damage:number};
type Spark={x:number;y:number;vx:number;vy:number;life:number;max:number};
const W=1280,H=720,SAVE='neon-void-v1';
const clamp=(n:number,a:number,b:number)=>Math.max(a,Math.min(b,n));
const distance=(a:{x:number;y:number},b:{x:number;y:number})=>Math.hypot(a.x-b.x,a.y-b.y);

export default function Home(){
 const canvas=useRef<HTMLCanvasElement>(null);const g=useRef<Game>(newGame());const [mode,setMode]=useState<Mode>('menu');const [high,setHigh]=useState(0);const [score,setScore]=useState(0);const [level,setLevel]=useState(1);const [sfx,setSfx]=useState(true);
 useEffect(()=>{try{const x=JSON.parse(localStorage.getItem(SAVE)||'{}');if(Number.isFinite(x.high))setHigh(x.high);setSfx(x.sfx!==false)}catch{}},[]);
 useEffect(()=>{const keys=new Set<string>();const down=(e:KeyboardEvent)=>{keys.add(e.key.toLowerCase());if(e.key.toLowerCase()==='p')g.current.mode=g.current.mode==='play'?'pause':'play';if(e.key.toLowerCase()==='shift')g.current.dash=true};const up=(e:KeyboardEvent)=>keys.delete(e.key.toLowerCase());addEventListener('keydown',down);addEventListener('keyup',up);(window as any).__keys=keys;return()=>{removeEventListener('keydown',down);removeEventListener('keyup',up)}},[]);
 useEffect(()=>{const c=canvas.current;if(!c)return;const ctx=c.getContext('2d');if(!ctx)return;let raf=0,last=performance.now();const resize=()=>{const d=Math.min(devicePixelRatio||1,2);c.width=c.clientWidth*d;c.height=c.clientHeight*d;ctx.setTransform(d,0,0,d,0,0)};resize();addEventListener('resize',resize);const frame=(now:number)=>{const dt=Math.min(.033,(now-last)/1000);last=now;const state=g.current;if(state.mode==='play')step(state,dt);draw(ctx,c.clientWidth,c.clientHeight,state);setMode(m=>m===state.mode?m:state.mode);if(state.mode==='over'){setScore(state.score);setLevel(state.level);setHigh(v=>Math.max(v,state.score))}raf=requestAnimationFrame(frame)};raf=requestAnimationFrame(frame);return()=>{cancelAnimationFrame(raf);removeEventListener('resize',resize)}},[]);
 const start=()=>{g.current=newGame();g.current.mode='play';setScore(0);setLevel(1);setMode('play');beep(220,.06,sfx)};const upgrade=(id:string)=>{const a=g.current;if(id==='damage')a.damage*=1.3;if(id==='rate')a.rate*=.78;if(id==='speed')a.speed*=1.2;if(id==='multi')a.multi++;if(id==='shield')a.shield+=50;if(id==='crit')a.crit+=.08;a.xp=0;a.pending=false;a.mode='play';setMode('play');beep(700,.08,sfx)};const saveSfx=(v:boolean)=>{setSfx(v);try{localStorage.setItem(SAVE,JSON.stringify({high,sfx:v}))}catch{}};
 const a=g.current;
 return <main className="game-shell"><div className="game-frame"><canvas ref={canvas}/>{(mode==='play'||mode==='pause'||mode==='upgrade')&&<HUD a={a} onPause={()=>{a.mode=a.mode==='play'?'pause':'play';setMode(a.mode)}} onDash={()=>{a.dash=true}}/>}
 {mode==='menu'&&<Overlay><span className="eyebrow">NEON VOID · ARENA SURVIVAL</span><h1 className="title">OUTLAST<br/>THE VOID.</h1><p className="subtitle">A fast neon roguelite built for one-more-run energy. Auto-fire, dodge, mutate, and survive escalating waves.</p><div className="button-row"><button className="btn primary" onClick={start}>ENTER ARENA</button><button className="btn" onClick={()=>setMode('howto')}>HOW TO PLAY</button><button className="btn" onClick={()=>setMode('settings')}>SETTINGS</button></div><p className="hint">WASD / arrows · SHIFT dash · P pause · High score {high}</p></Overlay>}
 {mode==='howto'&&<Overlay><Panel title="FIELD MANUAL"><div className="menu-list"><Stat b="MOVE" s="WASD / ARROWS · TOUCH JOYSTICK"/><Stat b="ATTACK" s="AUTO-FIRE TARGETS THE NEAREST ENEMY"/><Stat b="DASH" s="SHIFT OR TOUCH · SHORT INVULNERABILITY"/><Stat b="UPGRADE" s="LEVEL UP AND PICK ONE OF THREE MUTATIONS"/><Stat b="BOSS" s="EVERY 5 WAVES"/></div><button className="btn primary" onClick={()=>setMode('menu')}>BACK</button></Panel></Overlay>}
 {mode==='settings'&&<Overlay><Panel title="TUNE IN."><div className="menu-list"><button className="btn" onClick={()=>saveSfx(!sfx)}>SFX · {sfx?'ON':'OFF'}</button></div><button className="btn primary" onClick={()=>setMode('menu')}>BACK</button></Panel></Overlay>}
 {mode==='pause'&&<Overlay><Panel title="BREATHE."><p className="subtitle">The void waits. Your score does not.</p><div className="button-row"><button className="btn primary" onClick={()=>{a.mode='play';setMode('play')}}>RESUME</button><button className="btn" onClick={start}>RESTART</button><button className="btn" onClick={()=>{a.mode='menu';setMode('menu')}}>MENU</button></div></Panel></Overlay>}
 {mode==='upgrade'&&<Overlay><Panel title="CHOOSE YOUR EDGE."><span className="eyebrow">MUTATION · LEVEL {a.level}</span><div className="menu-list">{a.choices.map(x=><button className="btn" style={{textAlign:'left',padding:16}} key={x.id} onClick={()=>upgrade(x.id)}><b>{x.name}</b><span style={{display:'block',color:'#8f98b3',fontSize:12,marginTop:5}}>{x.desc}</span></button>)}</div></Panel></Overlay>}
 {mode==='over'&&<Overlay><Panel title="THE VOID WON."><div className="stat-grid"><Stat b="SCORE" s={String(score)}/><Stat b="HIGH SCORE" s={String(Math.max(high,score))}/><Stat b="SURVIVAL" s={fmt(a.time)}/><Stat b="LEVEL" s={String(level)}/></div><div className="button-row"><button className="btn primary" onClick={start}>RUN IT BACK</button><button className="btn" onClick={()=>setMode('menu')}>MENU</button></div></Panel></Overlay>}</div></main>
}

type Game={mode:Mode;p:{x:number;y:number};hp:number;maxHp:number;speed:number;damage:number;rate:number;fire:number;multi:number;crit:number;shield:number;dash:boolean;dashCd:number;time:number;wave:number;waveTime:number;spawn:number;score:number;level:number;xp:number;next:number;pending:boolean;enemies:Entity[];shots:Shot[];sparks:Spark[];choices:{id:string;name:string;desc:string}[]};
function newGame():Game{return{mode:'menu',p:{x:W/2,y:H/2},hp:100,maxHp:100,speed:240,damage:16,rate:.3,fire:0,multi:1,crit:.08,shield:0,dash:false,dashCd:0,time:0,wave:1,waveTime:0,spawn:.3,score:0,level:1,xp:0,next:70,pending:false,enemies:[],shots:[],sparks:[],choices:[]}}
function step(a:Game,dt:number){a.time+=dt;a.waveTime+=dt;a.spawn-=dt;a.fire-=dt;a.dashCd-=dt;const keys=(window as any).__keys as Set<string>;let dx=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0);let dy=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0);const touch=(window as any).__touch||{x:0,y:0};if(touch.x||touch.y){dx=touch.x;dy=touch.y}const len=Math.hypot(dx,dy)||1;if(len>1){dx/=len;dy/=len}if(a.dash&&a.dashCd<=0){a.dashCd=2;a.dash=false;burst(a,a.p.x,a.p.y,18)}const speed=a.speed*(a.dashCd>1.82?3.8:1);a.p.x=clamp(a.p.x+dx*speed*dt,30,W-30);a.p.y=clamp(a.p.y+dy*speed*dt,30,H-30);
 if(a.waveTime>28){a.wave++;a.waveTime=0;burst(a,a.p.x,a.p.y,30);if(a.wave%5===0)spawn(a,7)}if(a.spawn<=0){const count=1+Math.floor(a.wave/4);for(let i=0;i<count;i++)spawn(a,Math.random()<.2?Math.ceil(Math.random()*6):1);a.spawn=Math.max(.22,1.05-a.wave*.025)}if(a.fire<=0){a.fire=a.rate;const e=nearest(a.p,a.enemies);if(e){const ang=Math.atan2(e.y-a.p.y,e.x-a.p.x);for(let i=0;i<a.multi;i++){const s=(i-(a.multi-1)/2)*.12;const q=ang+s;a.shots.push({x:a.p.x,y:a.p.y,vx:Math.cos(q)*600,vy:Math.sin(q)*600,life:1.3,friendly:true,damage:a.damage*(Math.random()<a.crit?2:1)})}}}
 for(const b of a.shots){b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt}a.shots=a.shots.filter(b=>b.life>0&&b.x>-50&&b.x<W+50&&b.y>-50&&b.y<H+50);for(const e of a.enemies){const d=distance(e,a.p);const ang=Math.atan2(a.p.y-e.y,a.p.x-e.x);if(e.kind===5&&d<500){e.cool-=dt;if(e.cool<=0){e.cool=1.7;a.shots.push({x:e.x,y:e.y,vx:Math.cos(ang)*240,vy:Math.sin(ang)*240,life:3,friendly:false,damage:10})}e.x+=Math.cos(ang)*e.speed*.35*dt;e.y+=Math.sin(ang)*e.speed*.35*dt}else{e.x+=Math.cos(ang)*e.speed*dt;e.y+=Math.sin(ang)*e.speed*dt}if(d<e.r+15&&a.dashCd<1.82){if(a.shield>0)a.shield=Math.max(0,a.shield-20*dt);else a.hp-=(e.kind===7?25:12)*dt}}
 for(const b of a.shots.filter(x=>x.friendly)){for(const e of a.enemies){if(distance(b,e)<b.r+e.r){b.life=0;e.hp-=b.damage;if(e.hp<=0)kill(a,e)}}}for(const b of a.shots.filter(x=>!x.friendly)){if(distance(b,a.p)<19&&a.dashCd<1.82){b.life=0;if(a.shield>0)a.shield=Math.max(0,a.shield-20);else a.hp-=b.damage}}a.enemies=a.enemies.filter(e=>e.hp>0);for(const p of a.sparks){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.96;p.vy*=.96;p.life-=dt}a.sparks=a.sparks.filter(p=>p.life>0);
 if(a.xp>=a.next&&!a.pending){a.xp-=a.next;a.level++;a.next=Math.floor(a.next*1.22);a.pending=true;a.choices=makeChoices();a.mode='upgrade'}if(a.hp<=0){a.hp=0;a.mode='over';try{const old=JSON.parse(localStorage.getItem(SAVE)||'{}');localStorage.setItem(SAVE,JSON.stringify({high:Math.max(old.high||0,a.score),sfx:old.sfx!==false}))}catch{}}}
function spawn(a:Game,kind:number){const side=Math.floor(Math.random()*4);const x=side===0?-30:side===1?W+30:Math.random()*W;const y=side===2?-30:side===3?H+30:Math.random()*H;let r=14,h=30*(1+a.wave*.07),s=65+a.wave*2;if(kind===2){r=10;h=20;s=145}if(kind===3){r=25;h=190;s=38}if(kind===4){r=17;h=65;s=48}if(kind===5){r=7;h=10;s=180}if(kind===6){r=22;h=330;s=72}if(kind===7){r=58;h=3000+a.wave*260;s=48}a.enemies.push({x,y,r,hp:h,max:h,speed:s,kind,cool:1.2})}
function nearest(p:{x:number;y:number},arr:Entity[]){let best:Entity|undefined;let d=Infinity;for(const e of arr){const q=distance(p,e);if(q<d){d=q;best=e}}return best}function kill(a:Game,e:Entity){const v=e.kind===7?1500:e.kind===6?250:e.kind===3?70:e.kind===2?45:25;a.score+=v;a.xp+=e.kind===7?60:e.kind===6?28:8;burst(a,e.x,e.y,e.kind===7?55:12)}function burst(a:Game,x:number,y:number,n:number){for(let i=0;i<n;i++){const q=Math.random()*Math.PI*2,v=30+Math.random()*100;a.sparks.push({x,y,vx:Math.cos(q)*v,vy:Math.sin(q)*v,life:.3+Math.random()*.4,max:.7})}}function makeChoices(){const a=[{id:'damage',name:'OVERCLOCK',desc:'+30% damage'},{id:'rate',name:'RAPID CORE',desc:'Fire 22% faster'},{id:'speed',name:'VECTOR DRIVE',desc:'+20% movement speed'},{id:'multi',name:'SPLIT SHOT',desc:'+1 projectile per volley'},{id:'shield',name:'PHASE SHIELD',desc:'+50 shield'},{id:'crit',name:'RAZOR PROTOCOL',desc:'+8% critical chance'}];return a.sort(()=>Math.random()-.5).slice(0,3)}
function draw(c:CanvasRenderingContext2D,w:number,h:number,a:Game){c.clearRect(0,0,w,h);c.fillStyle='#050712';c.fillRect(0,0,w,h);c.strokeStyle='rgba(120,130,190,.045)';for(let x=0;x<w;x+=48){c.beginPath();c.moveTo(x,0);c.lineTo(x,h);c.stroke()}for(let y=0;y<h;y+=48){c.beginPath();c.moveTo(0,y);c.lineTo(w,y);c.stroke()}const sx=w/W,sy=h/H;c.save();c.scale(sx,sy);for(const p of a.sparks){c.globalAlpha=p.life/p.max;c.fillStyle='#7c75ff';c.beginPath();c.arc(p.x,p.y,3,0,Math.PI*2);c.fill()}c.globalAlpha=1;for(const b of a.shots){c.fillStyle=b.friendly?'#d7fbff':'#ff557f';c.beginPath();c.arc(b.x,b.y,4,0,Math.PI*2);c.fill()}for(const e of a.enemies){c.fillStyle=e.kind===7?'#ff4f88':e.kind===3?'#e78a4a':e.kind===5?'#55d9ff':e.kind===2?'#b06cff':e.kind===6?'#ff4fc5':'#ff5f7a';c.shadowBlur=e.kind>=6?20:8;c.shadowColor=c.fillStyle;c.beginPath();c.arc(e.x,e.y,e.r,0,Math.PI*2);c.fill();c.shadowBlur=0;if(e.hp<e.max){c.fillStyle='#26101b';c.fillRect(e.x-e.r,e.y-e.r-8,e.r*2,4);c.fillStyle='#ff668d';c.fillRect(e.x-e.r,e.y-e.r-8,e.r*2*e.hp/e.max,4)}}c.shadowBlur=28;c.shadowColor='#736cff';c.fillStyle='#8a84ff';c.beginPath();c.arc(a.p.x,a.p.y,15,0,Math.PI*2);c.fill();c.shadowBlur=0;if(a.shield>0){c.strokeStyle='#54dcff';c.beginPath();c.arc(a.p.x,a.p.y,29,0,Math.PI*2);c.stroke()}if(a.enemies.some(e=>e.kind===7)){const b=a.enemies.find(e=>e.kind===7)!;c.fillStyle='#21101a';c.fillRect(320,18,640,8);c.fillStyle='#ff4f88';c.fillRect(320,18,640*b.hp/b.max,8);c.fillStyle='#ffd1df';c.font='800 11px system-ui';c.textAlign='center';c.fillText('VOID WARDEN',640,14)}c.restore()}
function HUD({a,onPause,onDash}:{a:Game;onPause:()=>void;onDash:()=>void}){return <><div className="hud"><div className="hud-card"><div className="hud-line"><span>CORE</span><b>{Math.ceil(a.hp)}/{a.maxHp}</b></div><div className="bar"><div className="fill hp" style={{width:`${100*a.hp/a.maxHp}%`}}/></div><div className="hud-line" style={{marginTop:9}}><span>XP · LVL {a.level}</span><b>{Math.floor(a.xp)}/{a.next}</b></div><div className="bar"><div className="fill xp" style={{width:`${100*a.xp/a.next}%`}}/></div></div><div className="hud-card" style={{textAlign:'right'}}><div className="hud-line"><span>WAVE</span><b>{a.wave}</b></div><div className="hud-line"><span>SCORE</span><b>{a.score}</b></div><div className="hud-line"><span>TIME</span><b>{fmt(a.time)}</b></div></div></div><button className="btn pause" onClick={onPause}>Ⅱ</button><div className="touch"><div className="stick" onPointerDown={e=>{const r=e.currentTarget.getBoundingClientRect();(window as any).__touch={x:clamp((e.clientX-r.left-r.width/2)/(r.width/2),-1,1),y:clamp((e.clientY-r.top-r.height/2)/(r.height/2),-1,1)}} onPointerMove={e=>{const r=e.currentTarget.getBoundingClientRect();(window as any).__touch={x:clamp((e.clientX-r.left-r.width/2)/(r.width/2),-1,1),y:clamp((e.clientY-r.top-r.height/2)/(r.height/2),-1,1)}} onPointerUp={()=>{(window as any).__touch={x:0,y:0}}}><div className="knob"/></div><button className="dash" onPointerDown={onDash}>DASH</button></div></>}
function Overlay({children}:{children:React.ReactNode}){return <div className="overlay">{children}</div>}function Panel({title,children}:{title:string;children:React.ReactNode}){return <div className="panel"><span className="eyebrow">NEON VOID</span><h2 className="title" style={{fontSize:46}}>{title}</h2>{children}</div>}function Stat({b,s}:{b:string;s:string}){return <div className="stat"><b>{b}</b><span>{s}</span></div>}function fmt(t:number){return `${String(Math.floor(t/60)).padStart(2,'0')}:${String(Math.floor(t%60)).padStart(2,'0')}`}function beep(f:number,d:number,on:boolean){if(!on)return;try{const AC=window.AudioContext||(window as any).webkitAudioContext;const a=new AC(),o=a.createOscillator(),g=a.createGain();o.frequency.value=f;g.gain.value=.02;o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+d);setTimeout(()=>a.close(),d*1000+50)}catch{}}
