'use client';

import { useEffect, useRef, useState } from 'react';

type Mode='menu'|'playing'|'upgrade'|'paused'|'gameover'|'howto'|'settings';
type EnemyKind='chaser'|'runner'|'tank'|'shooter'|'swarm'|'elite'|'boss';
type Vec={x:number;y:number};
type Enemy=Vec&{kind:EnemyKind;r:number;hp:number;max:number;speed:number;shoot:number;phase:number;hit:number};
type Bullet=Vec&{vx:number;vy:number;life:number;damage:number;friendly:boolean;r:number};
type Particle=Vec&{vx:number;vy:number;life:number;max:number;size:number};
type Upgrade={id:string;name:string;desc:string;apply:()=>void};

const SAVE='neon-void-save-v1';
const rand=(a:number,b:number)=>a+Math.random()*(b-a);
const clamp=(n:number,a:number,b:number)=>Math.max(a,Math.min(b,n));
const dist=(a:Vec,b:Vec)=>Math.hypot(a.x-b.x,a.y-b.y);

export default function Home(){
  const canvasRef=useRef<HTMLCanvasElement>(null);
  const [mode,setMode]=useState<Mode>('menu');
  const [score,setScore]=useState(0); const [level,setLevel]=useState(1); const [high,setHigh]=useState(0);
  const [settings,setSettings]=useState({sfx:true,music:true});
  const state=useRef<GameState|null>(null); const keys=useRef(new Set<string>()); const touch=useRef<Vec>({x:0,y:0}); const dash=useRef(false);

  useEffect(()=>{try{const s=JSON.parse(localStorage.getItem(SAVE)||'{}');if(Number.isFinite(s.high))setHigh(s.high);if(typeof s.sfx==='boolean'||typeof s.music==='boolean')setSettings({sfx:s.sfx!==false,music:s.music!==false});}catch{localStorage.removeItem(SAVE)}} ,[]);

  useEffect(()=>{const down=(e:KeyboardEvent)=>{keys.current.add(e.key.toLowerCase());if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(e.key.toLowerCase()))e.preventDefault();if(e.key.toLowerCase()==='p')state.current?.togglePause();if(e.key.toLowerCase()==='shift')dash.current=true};const up=(e:KeyboardEvent)=>keys.current.delete(e.key.toLowerCase());window.addEventListener('keydown',down);window.addEventListener('keyup',up);return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up)}} ,[]);

  useEffect(()=>{const c=canvasRef.current;if(!c)return;const ctx=c.getContext('2d');if(!ctx)return;let raf=0;let last=performance.now();
    const resize=()=>{const d=Math.min(devicePixelRatio||1,2);c.width=c.clientWidth*d;c.height=c.clientHeight*d;ctx.setTransform(d,0,0,d,0,0)};resize();window.addEventListener('resize',resize);
    const loop=(now:number)=>{const dt=Math.min((now-last)/1000,.033);last=now;const s=state.current;if(s){if(s.mode==='playing')update(s,dt);draw(ctx,c.clientWidth,c.clientHeight,s)}raf=requestAnimationFrame(loop)};raf=requestAnimationFrame(loop);
    return()=>{cancelAnimationFrame(raf);window.removeEventListener('resize',resize)}
  },[]);

  const start=()=>{const s=newGame();state.current=s;setScore(0);setLevel(1);setMode('playing');s.mode='playing';playTone(220,.06,settings.sfx)};
  const finish=(s:GameState)=>{const hs=Math.max(high,s.score);setHigh(hs);setScore(s.score);setLevel(s.level);try{localStorage.setItem(SAVE,JSON.stringify({high:hs,sfx:settings.sfx,music:settings.music}))}catch{}setMode('gameover');s.mode='gameover';playTone(90,.25,settings.sfx)};
  const choose=(u:Upgrade)=>{u.apply();const s=state.current;if(s){s.levelXp=0;s.pendingLevel=false;s.mode='playing';setMode('playing');playTone(620,.08,settings.sfx)}};
  const pause=()=>{const s=state.current;if(!s)return;s.togglePause();setMode(s.mode)};
  const persistSettings=(v:{sfx:boolean;music:boolean})=>{setSettings(v);try{localStorage.setItem(SAVE,JSON.stringify({high,sfx:v.sfx,music:v.music}))}catch{}};

  const s=state.current; const upgrades=s?.upgradeChoices||[];
  return <main className="game-shell"><div className="game-frame">
    <canvas ref={canvasRef}/>
    {(mode==='playing'||mode==='paused'||mode==='upgrade')&&s&&<><div className="hud"><div className="hud-card"><div className="hud-line"><span>CORE</span><b>{Math.ceil(s.hp)}/{s.maxHp}</b></div><div className="bar"><div className="fill hp" style={{width:`${100*s.hp/s.maxHp}%`}}/></div><div className="hud-line" style={{marginTop:9}}><span>XP · LVL {s.level}</span><b>{Math.floor(s.levelXp)}/{s.nextXp}</b></div><div className="bar"><div className="fill xp" style={{width:`${100*s.levelXp/s.nextXp}%`}}/></div></div><div className="hud-card" style={{textAlign:'right'}}><div className="hud-line"><span>WAVE</span><b>{s.wave}</b></div><div className="hud-line"><span>SCORE</span><b>{s.score}</b></div><div className="hud-line"><span>TIME</span><b>{formatTime(s.time)}</b></div></div></div><button className="btn pause" onClick={pause}>{mode==='paused'?'▶':'Ⅱ'}</button><TouchControls onMove={(v)=>touch.current=v} onDash={()=>dash.current=true}/></>}
    {mode==='menu'&&<Overlay><span className="eyebrow">NEON VOID · ARENA SURVIVAL</span><h1 className="title">OUTLAST<br/>THE VOID.</h1><p className="subtitle">A relentless neon roguelite. Move, auto-fire, harvest energy, choose mutations, and survive the escalating swarm.</p><div className="button-row"><button className="btn primary" onClick={start}>ENTER ARENA</button><button className="btn" onClick={()=>setMode('howto')}>HOW TO PLAY</button><button className="btn" onClick={()=>setMode('settings')}>SETTINGS</button></div><p className="hint">WASD / arrows to move · SHIFT to dash · P to pause · High score {high}</p></Overlay>}
    {mode==='howto'&&<Overlay><div className="panel"><span className="eyebrow">FIELD MANUAL</span><h2 className="title" style={{fontSize:42}}>SURVIVE.</h2><div className="menu-list"><div className="stat"><b>Move</b><span>WASD / ARROWS · TOUCH JOYSTICK</span></div><div className="stat"><b>Attack</b><span>YOUR CORE FIRES AT THE NEAREST THREAT</span></div><div className="stat"><b>Dash</b><span>SHIFT OR TOUCH BUTTON · BRIEF INVULNERABILITY</span></div><div className="stat"><b>Mutate</b><span>LEVEL UP TO PICK ONE OF THREE BUILD-CHANGING UPGRADES</span></div><div className="stat"><b>Boss</b><span>EVERY 5 WAVES · TELEGRAPHED PHASE ATTACKS</span></div></div><button className="btn primary" onClick={()=>setMode('menu')}>BACK</button></div></Overlay>}
    {mode==='settings'&&<Overlay><div className="panel"><span className="eyebrow">SETTINGS</span><h2 className="title" style={{fontSize:42}}>TUNE IN.</h2><div className="menu-list"><button className="btn" onClick={()=>persistSettings({...settings,sfx:!settings.sfx})}>SFX · {settings.sfx?'ON':'OFF'}</button><button className="btn" onClick={()=>persistSettings({...settings,music:!settings.music})}>MUSIC · {settings.music?'ON':'OFF'}</button></div><button className="btn primary" onClick={()=>setMode('menu')}>BACK</button></div></Overlay>}
    {mode==='paused'&&<Overlay><div className="panel"><span className="eyebrow">SYSTEM PAUSED</span><h2 className="title" style={{fontSize:48}}>BREATHE.</h2><p className="subtitle">The void waits. Your score does not.</p><div className="button-row"><button className="btn primary" onClick={pause}>RESUME</button><button className="btn" onClick={start}>RESTART</button><button className="btn" onClick={()=>{setMode('menu');if(state.current)state.current.mode='menu'}}>MENU</button></div></div></Overlay>}
    {mode==='upgrade'&&<Overlay><div className="panel"><span className="eyebrow">MUTATION AVAILABLE · LEVEL {s?.level}</span><h2 className="title" style={{fontSize:46}}>CHOOSE<br/>YOUR EDGE.</h2><div className="menu-list">{upgrades.map((u,i)=><button className="btn" style={{textAlign:'left',padding:16}} key={u.id} onClick={()=>choose(u)}><b style={{display:'block',fontSize:16}}>{i+1}. {u.name}</b><span style={{display:'block',color:'#8f98b3',fontSize:12,marginTop:5}}>{u.desc}</span></button>)}</div></div></Overlay>}
    {mode==='gameover'&&<Overlay><div className="panel"><span className="eyebrow">SIGNAL LOST</span><h2 className="title" style={{fontSize:56}}>THE VOID<br/>WON.</h2><div className="stat-grid"><div className="stat"><span>Score</span><b>{score}</b></div><div className="stat"><span>High Score</span><b>{high}</b></div><div className="stat"><span>Survival</span><b>{formatTime(s?.time||0)}</b></div><div className="stat"><span>Level</span><b>{level}</b></div></div><div className="button-row"><button className="btn primary" onClick={start}>RUN IT BACK</button><button className="btn" onClick={()=>setMode('menu')}>MENU</button></div></div></Overlay>}
  </div></main>
}

function Overlay({children}:{children:React.ReactNode}){return <div className="overlay">{children}</div>}
function TouchControls({onMove,onDash}:{onMove:(v:Vec)=>void;onDash:()=>void}){const active=useRef(false);const update=(e:React.PointerEvent<HTMLDivElement>)=>{const r=e.currentTarget.getBoundingClientRect();const x=clamp((e.clientX-r.left-r.width/2)/(r.width/2),-1,1);const y=clamp((e.clientY-r.top-r.height/2)/(r.height/2),-1,1);onMove({x,y})};return <div className="touch"><div className="stick" onPointerDown={e=>{active.current=true;e.currentTarget.setPointerCapture(e.pointerId);update(e)}} onPointerMove={e=>{if(active.current)update(e)}} onPointerUp={()=>{active.current=false;onMove({x:0,y:0})}}><div className="knob"/></div><button className="dash" onPointerDown={onDash}>DASH</button></div>}

interface GameState{mode:Mode;player:Vec;hp:number;maxHp:number;speed:number;damage:number;fireRate:number;fireTimer:number;bulletSpeed:number;multishot:number;crit:number;shield:number;dashCd:number;dashTime:number;time:number;wave:number;waveTimer:number;spawnTimer:number;score:number;kills:number;level:number;levelXp:number;nextXp:number;pendingLevel:boolean;enemies:Enemy[];bullets:Bullet[];particles:Particle[];floating:{x:number;y:number;text:string;life:number}[];upgradeChoices:Upgrade[];shake:number;bossSpawned:number;togglePause:()=>void}
function newGame():GameState{return{mode:'menu',player:{x:640,y:360},hp:100,maxHp:100,speed:240,damage:16,fireRate:.32,fireTimer:0,bulletSpeed:570,multishot:1,crit:.08,shield:0,dashCd:0,dashTime:0,time:0,wave:1,waveTimer:0,spawnTimer:.2,score:0,kills:0,level:1,levelXp:0,nextXp:70,pendingLevel:false,enemies:[],bullets:[],particles:[],floating:[],upgradeChoices:[],shake:0,bossSpawned:0,togglePause(){this.mode=this.mode==='playing'?'paused':'playing'}}}

function update(s:GameState,dt:number){s.time+=dt;s.waveTimer+=dt;s.spawnTimer-=dt;s.fireTimer-=dt;s.dashCd-=dt;s.shake=Math.max(0,s.shake-dt*18);const W=1280,H=720;
  if(s.waveTimer>28){s.wave++;s.waveTimer=0;burst(s,s.player.x,s.player.y,28,2);if(s.wave%5===0)spawnEnemy(s,'boss');}
  const input={x:0,y:0};const k=(globalThis as unknown as {__keys?:Set<string>}).__keys; // fallback is filled below by direct DOM state
  if(typeof window!=='undefined'){input.x=(window.event instanceof KeyboardEvent?0:0)}
  // Read keyboard without React renders.
  const pressed=(key:string)=>document.querySelector(':focus')?false:(window as unknown as {__nvKeys?:Set<string>}).__nvKeys?.has(key)||false;
  input.x=(pressed('d')||pressed('arrowright')?1:0)-(pressed('a')||pressed('arrowleft')?1:0);input.y=(pressed('s')||pressed('arrowdown')?1:0)-(pressed('w')||pressed('arrowup')?1:0);
  const tc=(window as unknown as {__nvTouch?:Vec}).__nvTouch||{x:0,y:0};if(tc.x||tc.y){input.x=tc.x;input.y=tc.y}const mag=Math.hypot(input.x,input.y)||1;if(mag>1){input.x/=mag;input.y/=mag}
  if((window as unknown as {__nvDash?:boolean}).__nvDash&&s.dashCd<=0){s.dashTime=.18;s.dashCd=2.2;(window as unknown as {__nvDash?:boolean}).__nvDash=false;burst(s,s.player.x,s.player.y,18,3);playTone(180,.08,true)}
  const speed=s.speed*(s.dashTime>0?3.7:1);s.player.x=clamp(s.player.x+input.x*speed*dt,35,W-35);s.player.y=clamp(s.player.y+input.y*speed*dt,35,H-35);s.dashTime=Math.max(0,s.dashTime-dt);
  if(s.fireTimer<=0){s.fireTimer=s.fireRate;const target=nearest(s.player,s.enemies);if(target){const base=Math.atan2(target.y-s.player.y,target.x-s.player.x);for(let i=0;i<s.multishot;i++){const spread=(i-(s.multishot-1)/2)*.12;const a=base+spread;const crit=Math.random()<s.crit;s.bullets.push({x:s.player.x,y:s.player.y,vx:Math.cos(a)*s.bulletSpeed,vy:Math.sin(a)*s.bulletSpeed,life:1.4,damage:s.damage*(crit?2:1),friendly:true,r:4})}playTone(520,.025,true)}}
  if(s.spawnTimer<=0){const count=1+Math.floor(s.wave/4);for(let i=0;i<count;i++)spawnEnemy(s,chooseKind(s));s.spawnTimer=Math.max(.2,1.05-s.wave*.025)}
  for(const b of s.bullets){b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt}s.bullets=s.bullets.filter(b=>b.life>0&&b.x>-30&&b.x<W+30&&b.y>-30&&b.y<H+30);
  for(const e of s.enemies){e.hit=Math.max(0,e.hit-dt);const d=dist(e,s.player);if(e.kind==='shooter'&&d<520){const a=Math.atan2(s.player.y-e.y,s.player.x-e.x);e.vx=Math.cos(a)*e.speed*.35;e.vy=Math.sin(a)*e.speed*.35;e.shoot-=dt;if(e.shoot<=0){e.shoot=1.8;const a2=Math.atan2(s.player.y-e.y,s.player.x-e.x);s.bullets.push({x:e.x,y:e.y,vx:Math.cos(a2)*230,vy:Math.sin(a2)*230,life:3,damage:10,friendly:false,r:5})}}else{const a=Math.atan2(s.player.y-e.y,s.player.x-e.x);e.vx=Math.cos(a)*e.speed;e.vy=Math.sin(a)*e.speed}e.x+=e.vx*dt;e.y+=e.vy*dt;e.phase+=dt*e.speed/100;if(d<e.r+16&&s.dashTime<=0){if(s.shield>0){s.shield=Math.max(0,s.shield-20*dt)}else{s.hp-=e.kind==='boss'?24*dt:12*dt}s.shake=1}}
  for(const b of s.bullets.filter(x=>x.friendly)){for(const e of s.enemies){if(dist(b,e)<b.r+e.r){e.hp-=b.damage;b.life=0;e.hit=.08;burst(s,b.x,b.y,4,1);if(e.hp<=0){kill(s,e)}}}}
  for(const b of s.bullets.filter(x=>!x.friendly)){if(dist(b,s.player)<b.r+14&&s.dashTime<=0){b.life=0;if(s.shield>0)s.shield=Math.max(0,s.shield-18);else s.hp-=b.damage;burst(s,s.player.x,s.player.y,6,1);s.shake=4}}
  s.enemies=s.enemies.filter(e=>e.hp>0);for(const p of s.particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.96;p.vy*=.96;p.life-=dt}s.particles=s.particles.filter(p=>p.life>0);for(const f of s.floating){f.y-=22*dt;f.life-=dt}s.floating=s.floating.filter(f=>f.life>0);
  if(s.levelXp>=s.nextXp&&!s.pendingLevel){s.levelXp-=s.nextXp;s.level++;s.nextXp=Math.floor(s.nextXp*1.22);s.pendingLevel=true;s.upgradeChoices=makeUpgrades(s);s.mode='upgrade';burst(s,s.player.x,s.player.y,40,3);playTone(760,.16,true)}
  if(s.hp<=0){s.hp=0;finishGame(s)}
}
function finishGame(s:GameState){s.mode='gameover';burst(s,s.player.x,s.player.y,80,4);s.shake=12}
function kill(s:GameState,e:Enemy){const value=e.kind==='boss'?1500:e.kind==='elite'?250:e.kind==='tank'?70:e.kind==='runner'?45:25;s.score+=value;s.kills++;s.levelXp+=e.kind==='boss'?60: e.kind==='elite'?28:8; s.floating.push({x:e.x,y:e.y-20,text:`+${value}`,life:.8});burst(s,e.x,e.y,e.kind==='boss'?60:14,e.kind==='boss'?4:2);if(e.kind==='boss')s.bossSpawned++;playTone(e.kind==='boss'?70:180,.04,true)}
function chooseKind(s:GameState):EnemyKind{const r=Math.random();if(s.wave<3)return r<.8?'chaser':'runner';if(r<.5)return'chaser';if(r<.7)return'runner';if(r<.84)return'shooter';if(r<.94)return'tank';if(r<.985)return'swarm';return'elite'}
function spawnEnemy(s:GameState,kind:EnemyKind){const W=1280,H=720;let x=0,y=0;const side=Math.floor(Math.random()*4);if(side===0){x=-30;y=rand(0,H)}if(side===1){x=W+30;y=rand(0,H)}if(side===2){x=rand(0,W);y=-30}if(side===3){x=rand(0,W);y=H+30}const scale=1+s.wave*.07;let r=14,hp=30*scale,spd=65+ s.wave*2;if(kind==='runner'){r=10;hp=20*scale;spd=145+s.wave*3}if(kind==='tank'){r=25;hp=190*scale;spd=38+s.wave}if(kind==='shooter'){r=17;hp=65*scale;spd=48+s.wave}if(kind==='swarm'){r=7;hp=10*scale;spd=180+s.wave*3}if(kind==='elite'){r=22;hp=330*scale;spd=72+s.wave*2}if(kind==='boss'){r=58;hp=3000+ s.wave*260;spd=48+s.wave; s.bossSpawned=s.wave}s.enemies.push({x,y,kind,r,hp,max:hp,speed:spd,shoot:rand(.5,1.8),phase:rand(0,6),hit:0})}
function nearest(p:Vec,arr:Enemy[]){let best:Enemy|undefined;let d=Infinity;for(const e of arr){const q=dist(p,e);if(q<d){d=q;best=e}}return best}
function burst(s:GameState,x:number,y:number,n:number,power:number){for(let i=0;i<n;i++){const a=rand(0,Math.PI*2),v=rand(30,120)*power;s.particles.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,life:rand(.25,.7),max:.7,size:rand(1.5,4)*power})}}
function makeUpgrades(s:GameState):Upgrade[]{const all:Upgrade[]=[{id:'damage',name:'Overclock',desc:'+28% weapon damage',apply:()=>s.damage*=1.28},{id:'rate',name:'Rapid Core',desc:'Fire 22% faster',apply:()=>s.fireRate*=.78},{id:'multi',name:'Split Shot',desc:'+1 projectile per volley',apply:()=>s.multishot++},{id:'speed',name:'Vector Drive',desc:'+20% movement speed',apply:()=>s.speed*=1.2},{id:'crit',name:'Razor Protocol',desc:'+8% critical chance',apply:()=>s.crit+=.08},{id:'shield',name:'Phase Shield',desc:'+45 temporary shield',apply:()=>s.shield+=45},{id:'health',name:'Nanite Bloom',desc:'+30 max HP and heal 30',apply:()=>{s.maxHp+=30;s.hp=Math.min(s.maxHp,s.hp+30)}},{id:'bullet',name:'Mass Driver',desc:'+18% projectile speed and +4 damage',apply:()=>{s.bulletSpeed*=1.18;s.damage+=4}}];return all.sort(()=>Math.random()-.5).slice(0,3)}
function draw(ctx:CanvasRenderingContext2D,W:number,H:number,s:GameState){ctx.clearRect(0,0,W,H);ctx.fillStyle='#050712';ctx.fillRect(0,0,W,H);const g=ctx.createRadialGradient(s.player.x,s.player.y,20,s.player.x,s.player.y,520);g.addColorStop(0,'rgba(84,92,255,.12)');g.addColorStop(1,'rgba(5,7,18,0)');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.save();if(s.shake>0)ctx.translate(rand(-s.shake,s.shake),rand(-s.shake,s.shake));
  ctx.strokeStyle='rgba(120,130,190,.045)';ctx.lineWidth=1;for(let x=0;x<W;x+=48){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<H;y+=48){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}
  for(const p of s.particles){ctx.globalAlpha=clamp(p.life/p.max,0,1);ctx.fillStyle='#7c75ff';ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;
  for(const b of s.bullets){ctx.strokeStyle=b.friendly?'#7de7ff':'#ff557f';ctx.lineWidth=b.r*1.5;ctx.globalAlpha=.35;ctx.beginPath();ctx.moveTo(b.x-b.vx*.025,b.y-b.vy*.025);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.globalAlpha=1;ctx.fillStyle=b.friendly?'#d7fbff':'#ff557f';ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,Math.PI*2);ctx.fill()}
  for(const e of s.enemies){const boss=e.kind==='boss';ctx.save();ctx.translate(e.x,e.y);if(boss){ctx.rotate(e.phase*.35);ctx.strokeStyle='#ff4f88';ctx.lineWidth=5;ctx.shadowBlur=22;ctx.shadowColor='#ff3f83';ctx.strokeRect(-e.r*.7,-e.r*.7,e.r*1.4,e.r*1.4);ctx.fillStyle='#211025';ctx.fillRect(-e.r*.45,-e.r*.45,e.r*.9,e.r*.9)}else{ctx.fillStyle=e.kind==='tank'?'#e78a4a':e.kind==='shooter'?'#55d9ff':e.kind==='runner'?'#b06cff':e.kind==='elite'?'#ff4fc5':'#ff5f7a';ctx.shadowBlur=e.kind==='elite'?18:10;ctx.shadowColor=ctx.fillStyle;ctx.beginPath();const sides=e.kind==='tank'?8:e.kind==='swarm'?5:6;for(let i=0;i<sides;i++){const a=i*Math.PI*2/sides+e.phase*.08;const rr=e.r*(i%2?0.88:1);const px=Math.cos(a)*rr,py=Math.sin(a)*rr;i?ctx.lineTo(px,py):ctx.moveTo(px,py)}ctx.closePath();ctx.fill()}ctx.shadowBlur=0;if(e.hp<e.max){ctx.fillStyle='rgba(0,0,0,.6)';ctx.fillRect(-e.r,-e.r-9,e.r*2,4);ctx.fillStyle='#ff668d';ctx.fillRect(-e.r,-e.r-9,e.r*2*(e.hp/e.max),4)}ctx.restore()}
  const pulse=1+Math.sin(s.time*5)*.04;ctx.save();ctx.translate(s.player.x,s.player.y);ctx.scale(pulse,pulse);ctx.shadowBlur=28;ctx.shadowColor='#736cff';ctx.fillStyle=s.dashTime>0?'#fff':'#8a84ff';ctx.beginPath();ctx.arc(0,0,15,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#c9c6ff';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,23+Math.sin(s.time*3)*2,0,Math.PI*2);ctx.stroke();if(s.shield>0){ctx.strokeStyle='rgba(84,220,255,.7)';ctx.beginPath();ctx.arc(0,0,30,0,Math.PI*2);ctx.stroke()}ctx.restore();
  for(const f of s.floating){ctx.globalAlpha=f.life/.8;ctx.fillStyle='#fff';ctx.font='bold 12px system-ui';ctx.textAlign='center';ctx.fillText(f.text,f.x,f.y)}ctx.globalAlpha=1;ctx.restore();if(s.enemies.some(e=>e.kind==='boss')){const b=s.enemies.find(e=>e.kind==='boss')!;ctx.fillStyle='rgba(0,0,0,.5)';ctx.fillRect(W*.25,18,W*.5,8);ctx.fillStyle='#ff4f88';ctx.fillRect(W*.25,18,W*.5*(b.hp/b.max),8);ctx.fillStyle='#ffd1df';ctx.font='800 11px system-ui';ctx.textAlign='center';ctx.fillText('VOID WARDEN',W/2,14)}}
function formatTime(t:number){const m=Math.floor(t/60).toString().padStart(2,'0');const sec=Math.floor(t%60).toString().padStart(2,'0');return `${m}:${sec}`}
function playTone(freq:number,duration:number,enabled=true){if(!enabled||typeof window==='undefined')return;try{const AC=window.AudioContext||(window as unknown as {webkitAudioContext:typeof AudioContext}).webkitAudioContext;const ac=new AC();const o=ac.createOscillator(),g=ac.createGain();o.frequency.value=freq;o.type='sine';g.gain.setValueAtTime(.025,ac.currentTime);g.gain.exponentialRampToValueAtTime(.001,ac.currentTime+duration);o.connect(g);g.connect(ac.destination);o.start();o.stop(ac.currentTime+duration);setTimeout(()=>void ac.close(),duration*1000+80)}catch{}}

// Bridge input state to the render loop without React updates.
if(typeof window!=='undefined' && !(window as unknown as {__nvInit?:boolean}).__nvInit){(window as unknown as {__nvInit:boolean}).__nvInit=true;(window as unknown as {__nvKeys:Set<string>}).__nvKeys=new Set();window.addEventListener('keydown',e=>(window as unknown as {__nvKeys:Set<string>}).__nvKeys.add(e.key.toLowerCase()));window.addEventListener('keyup',e=>(window as unknown as {__nvKeys:Set<string>}).__nvKeys.delete(e.key.toLowerCase()));}
